version: '2'
services:
    spark:
        image: "velvia/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1"
        ports:
             - "8090:8090"
        volumes:
             - ".:/mounted"

    golang:
        links:
            -  "spark"
        build:
            context: .
        ports:
             - "8080:8080"
        volumes:
             - ".:/mounted"

